name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        cd nes-emulator
        cargo --version
    - uses: actions-rs/toolchain@v1.0.6
    - name: Build
      run: |
        cargo --version
        cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
